- id: composer
  name: composer
  description: Run Composer command
  entry: ./hooks/composer.sh
  language: script
  pass_filenames: false
  args: []

- id: declare_strict_types
  name: declare_strict_types
  description: Checks on "declare(strict_types=1)"
  entry: php ./hooks/declare_strict_types.php
  language: script
  pass_filenames: true
  args: []

